const stockSilla = [
    {
        id: 1,
        producto: "sillas eames",
        img: `<img src="../img/sillas/sillasEames.jpg">`,
        cantidad: 1,
        precio: 20000,
        categoria: "silla",
    },
    {
        id: 2,
        producto: "sillas eames con amohadon",
        img: `<img src="../img/sillas/sillasEamesConAlmohadon.jpg">`,
        cantidad: 1,
        precio: 21000,
        categoria: "silla",
    },
    {
        id: 3,
        producto: "sillas eames ecocuero tapizadas",
        img: `<img src="../img/sillas/sillasEamesEcocueroTapizadas.jpeg">`,
        cantidad: 1,
        precio: 20500,
        categoria: "silla",
    },
    {
        id: 4,
        producto: "sillas eames para niños",
        img: `<img src="../img/sillas/sillasEamesParaNiños.jpg">`,
        cantidad: 1,
        precio: 21000,
        categoria: "silla",
    },
    {
        id: 5,
        producto: "sillas ecocuero",
        img: `<img src="../img/sillas/sillasEcocuero.jpg">`,
        cantidad: 1,
        precio: 21000,
        categoria: "silla",
    },
    {
        id: 6,
        producto: "sillas eiffel",
        img: `<img src="../img/sillas/sillasEiffel.jpg">`,
        cantidad: 1,
        precio: 21000,
        categoria: "silla",
    },
    {
        id: 7,
        producto: "sillas hexagonales",
        img: `<img src="../img/sillas/sillasHexagonales.jpg">`,
        cantidad: 1,
        precio: 21000,
        categoria: "silla",
    },
    {
        id: 8,
        producto: "sillas tolix",
        img: `<img src="../img/sillas/sillasTolix.jpg">`,
        cantidad: 1,
        precio: 21000,
        categoria: "silla",
    },
    {
        id: 9,
        producto: "sillas tulip con almohadon",
        img: `<img src="../img/sillas/sillasTulipConAlmohadon.jpg">`,
        cantidad: 1,
        precio: 21000,
        categoria: "silla",
    },
    {
        id: 10,
        producto: "sillas tulip con almohadon tapizadas en lino",
        img: `<img src="../img/sillas/sillasTulipConAlmohadonTapizadasEnLino.jpg">`,
        cantidad: 1,
        precio: 21000,
        categoria: "silla",
    },
    {
        id: 11,
        producto: "banquetas eames",
        img: `<img src="../img/sillas/banquetasEames.jpg">`,
        cantidad: 1,
        precio: 21000,
        categoria: "silla",
    },
    {
        id: 12,
        producto: "banquetas tolix",
        img: `<img src="../img/sillas/banquetasTolix.jpg">`,
        cantidad: 1,
        precio: 21000,
        categoria: "silla",
    },
    {
        id: 13,
        producto: "taburete tolix",
        img: `<img src="../img/sillas/tabuleteTolix.jpg">`,
        cantidad: 1,
        precio: 21000,
        categoria: "silla",
    }
];

const StockMesa = [
    {
        id: 1,
        producto: "mesa eames rectangular laqueada",
        img: `<img src="../img/mesas/mesaEamesRectangularLaqueada.jpg">`,
        cantidad: 1,
        precio: 30000,
        categoria: "mesa",
    },
    {
        id: 2,
        producto: "mesa eames redonda de vidrio",
        img: `<img src="../img/mesas/mesaEamesRedondaDeVidrio.jpg">`,
        cantidad: 1,
        precio: 31000,
        categoria: "mesa",
    },
    {
        id: 3,
        producto: "mesa eames redonda laqueada",
        img: `<img src="../img/mesas/mesaRedondaLaqueada.jpg">`,
        cantidad: 1,
        precio: 30500,
        categoria: "mesa",
    },
    {
        id: 4,
        producto: "mesa eames para niños",
        img: `<img src="../img/mesas/mesaEamesParaNiños.jpg">`,
        cantidad: 1,
        precio: 30500,
        categoria: "mesa",
    },
    {
        id: 5,
        producto: "mesa tulip rectangular de vidrio",
        img: `<img src="../img/mesas/mesaTulipRectangularDeVidrio.jpeg">`,
        cantidad: 1,
        precio: 30500,
        categoria: "mesa",
    }
];
const StockSillones = [
    {
        id: 1,
        producto: "sillon eames",
        img: `<img src="../img/sillon/sillonEames.jpg">`,
        cantidad: 1,
        precio: 30500,
        categoria: "sillones",
    },
    {
        id: 2,
        producto: "sillon eiffel",
        img: `<img src="../img/sillon/sillonEiffel.jpg">`,
        cantidad: 1,
        precio: 30500,
        categoria: "sillones",
    },
    {
        id: 3,
        producto: "sillon mecedora",
        img: `<img src="../img/sillon/sillonMecedora.jpg">`,
        cantidad: 1,
        precio: 30500,
        categoria: "sillones",
    },
    {
        id: 4,
        producto: "sillon tulip suizo",
        img: `<img src="../img/sillon/sillonTulipSuizo.jpg">`,
        cantidad: 1,
        precio: 30500,
        categoria: "sillones",
    }
];